<?php
/**
 * Class WP_Legal_Pages_Public_Test class
 *
 * @package wplegalpages
 * @subpackage wplegalpages/tests
 */

/**
 * Require WP_Legal_Pages_Public class.
 */
require_once plugin_dir_path( dirname( __FILE__ ) ) . 'public/class-wp-legal-pages-public.php';

/**
 * Class WP_Legal_Pages_Public class test cases
 */
class WP_Legal_Pages_Public_Test extends WP_UnitTestCase {

	/**
	 * The WP_Legal_Pages_Public class instance.
	 *
	 * @access public
	 * @var    string    $wplegalpages_public class instance.
	 */
	public static $wplegalpages_public;

	/**
	 * Set up function.
	 *
	 * @param WP_UnitTest_Factory $factory helper for unit test functionality.
	 */
	public static function wpSetUpBeforeClass( WP_UnitTest_Factory $factory ) {
		self::$wplegalpages_public = new WP_Legal_Pages_Public( 'wp-legal-pages', '2.5.2' );
	}

	/**
	 * Test for constructor function
	 */
	public function test_constructor() {
		$obj = new WP_Legal_Pages_Public( 'wp-legal-pages', '2.5.2' );
		$this->assertTrue( $obj instanceof WP_Legal_Pages_Public );
	}

	/**
	 * Test for enqueue_styles function
	 */
	public function test_enqueue_styles() {
		self::$wplegalpages_public->enqueue_styles();
		$this->assertTrue( true );
	}

	/**
	 * Test for enqueue_scripts function
	 */
	public function test_enqueue_scripts() {
		self::$wplegalpages_public->enqueue_scripts();
		$this->assertTrue( true );
	}

	/**
	 * Test for wplegal_post_generate function
	 */
	public function test_wplegal_post_generate() {
		$post_id = self::factory()->post->create( array( 'post_type' => 'page' ) );
		$url     = get_permalink( $post_id );
		$this->go_to( $url );
		update_post_meta( $post_id, 'is_legal', 'yes' );
		$input_content  = '<div class = "content"></div>';
		$output_content = self::$wplegalpages_public->wplegal_post_generate( $input_content );
		$generated_text = "<div style='font-size: 0.7em;'><i>" . get_the_title( get_post( $post_id ) ) . " generated by <a href='https://club.wpeka.com/product/wplegalpages/?utm_source=generated-page&utm_medium=credit-link' rel='nofollow' target='_blank'>WPLegalPages</a></i></div>";
		$this->assertEquals( $input_content . $generated_text, $output_content );
	}
}
