<?php
/**
 * Class WP_Legal_Pages_Public_Test class
 *
 * @package wplegalpages
 * @subpackage wplegalpages/tests
 */

/**
 * Require WP_Legal_Pages_Public class.
 */
require_once plugin_dir_path( dirname( __FILE__ ) ) . 'public/class-wp-legal-pages-public.php';

/**
 * Class WP_Legal_Pages_Public class test cases
 */
class WP_Legal_Pages_Public_Test extends WP_UnitTestCase {

	/**
	 * The WP_Legal_Pages_Public class instance.
	 *
	 * @access public
	 * @var    string    $wplegalpages_public class instance.
	 */
	public static $wplegalpages_public;

	/**
	 * Created legal pages.
	 *
	 * @since  1.0.0
	 * @access public
	 * @var    string $lp_ids legalpage ids.
	 */
	public static $lp_ids;

	/**
	 * Set up function.
	 *
	 * @param WP_UnitTest_Factory $factory helper for unit test functionality.
	 */
	public static function wpSetUpBeforeClass( WP_UnitTest_Factory $factory ) {
		self::$lp_ids              = $factory->post->create_many( 2, array( 'post_type' => 'page' ) );
		self::$wplegalpages_public = new WP_Legal_Pages_Public( 'wp-legal-pages', '2.6.0' );
	}

	/**
	 * Test for constructor function
	 */
	public function test_constructor() {
		$obj = new WP_Legal_Pages_Public( 'wp-legal-pages', '2.6.0' );
		$this->assertTrue( $obj instanceof WP_Legal_Pages_Public );
	}

	/**
	 * Test for enqueue_styles function
	 */
	public function test_enqueue_styles() {
		self::$wplegalpages_public->enqueue_styles();
		$this->assertTrue( true );
	}

	/**
	 * Test for enqueue_scripts function
	 */
	public function test_enqueue_scripts() {
		self::$wplegalpages_public->enqueue_scripts();
		$this->assertTrue( true );
	}

	/**
	 * Test for wplegal_post_generate function
	 */
	public function test_wplegal_post_generate() {
		$post_id = self::factory()->post->create( array( 'post_type' => 'page' ) );
		$url     = get_permalink( $post_id );
		$this->go_to( $url );
		update_post_meta( $post_id, 'is_legal', 'yes' );
		$input_content  = '<div class = "content"></div>';
		$output_content = self::$wplegalpages_public->wplegal_post_generate( $input_content );
		$generated_text = "<div style='font-size: 0.7em;'><i>" . get_the_title( get_post( $post_id ) ) . " generated by <a href='https://club.wpeka.com/product/wplegalpages/?utm_source=generated-page&utm_medium=credit-link' rel='nofollow' target='_blank'>WPLegalPages</a></i></div>";
		$this->assertEquals( $input_content . $generated_text, $output_content );
	}

	/**
	 * Test for wp_legalpages_show_footer_message
	 */
	public function test_wp_legalpages_show_footer_message() {
		$lp_footer_options = array(
			'show_footer'        => '1',
			'footer_text_align'  => 'center',
			'footer_separator'   => '*',
			'footer_bg_color'    => '#ffffff',
			'footer_text_color'  => '#888888',
			'footer_link_color'  => '#888888',
			'footer_font'        => 'Arial',
			'footer_font_id'     => 'Arial',
			'footer_font_size'   => '20',
			'footer_new_tab'     => '0',
			'footer_legal_pages' => 'Privacy Policy',
			'footer_custom_css'  => '#wplegalpages_footer_links_container{text-decoration: underline};',
		);
		update_option( 'lp_footer_options', $lp_footer_options );
		ob_start();
		self::$wplegalpages_public->wp_legalpages_show_footer_message();
		$html = ob_get_clean();
		$this->assertTrue( is_string( $html ) && ( wp_strip_all_tags( $html ) !== $html ) );
	}

	/**
	 * Test lp_banner_contents_display
	 */
	public function test_lp_banner_contents_display() {
		$_COOKIE[ 'wplegalpages-update-notice-' . self::$lp_ids[0] ] = 'wplegalpages-update-notice-' . self::$lp_ids[0];
		$lp_banner_options = array(
			'bar_position'            => 'top',
			'bar_type'                => 'static',
			'banner_bg_color'         => '#ffffff',
			'banner_font'             => 'Roboto',
			'banner_font_id'          => 'Roboto',
			'banner_text_color'       => '#000000',
			'banner_font_size'        => 18,
			'banner_link_color'       => '#000000',
			'bar_num_of_days'         => 1,
			'banner_custom_css'       => '.wplegalpages_banner_content { height: 100px; }',
			'banner_close_message'    => 'X',
			'banner_message'          => 'The page [wplegalpages_page_title] has been updated',
			'banner_multiple_message' => 'The pages [wplegalpages_page_title] has been updated',
		);
		update_option( 'lp_banner_options', $lp_banner_options );
		ob_start();
		self::$wplegalpages_public->lp_banner_contents_display();
		$html = ob_get_clean();
		$this->assertTrue( is_string( $html ) && ( wp_strip_all_tags( $html ) !== $html ) );
		$_COOKIE[ 'wplegalpages-update-notice-' . self::$lp_ids[1] ] = 'wplegalpages-update-notice-' . self::$lp_ids[1];
		ob_start();
		self::$wplegalpages_public->lp_banner_contents_display();
		$html = ob_get_clean();
		$this->assertTrue( is_string( $html ) && ( wp_strip_all_tags( $html ) !== $html ) );
	}

	/**
	 * Test for wplegal_announce_bar_content
	 */
	public function test_wplegal_announce_bar_content() {
		$lp_banner_options = array(
			'show_banner'             => '1',
			'bar_position'            => 'top',
			'bar_type'                => 'static',
			'banner_bg_color'         => '#ffffff',
			'banner_font'             => 'Roboto',
			'banner_font_id'          => 'Roboto',
			'banner_text_color'       => '#000000',
			'banner_font_size'        => 18,
			'banner_link_color'       => '#000000',
			'bar_num_of_days'         => 1,
			'banner_custom_css'       => '.wplegalpages_banner_content { height: 100px; }',
			'banner_close_message'    => 'X',
			'banner_message'          => 'The page [wplegalpages_page_title] has been updated',
			'banner_multiple_message' => 'The pages [wplegalpages_page_title] has been updated',
		);
		update_option( 'lp_banner_options', $lp_banner_options );
		$_COOKIE[ 'wplegalpages-update-notice-' . self::$lp_ids[0] ] = 'wplegalpages-update-notice-' . self::$lp_ids[0];
		ob_start();
		self::$wplegalpages_public->wplegal_announce_bar_content();
		$html = ob_get_clean();
		$this->assertTrue( is_string( $html ) && ( wp_strip_all_tags( $html ) !== $html ) );
	}
}
